schemaVersion: 2.2.0
metadata:
  name: python-ds
  version: 2.1.0
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.4
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      memoryLimit: 2G
      mountSources: true
  - name: venv
    volume:
      size: 1G
commands:
  - id: run
    exec:
      label: "Run the application"
      component: python
      workingDir: ${PROJECTS_ROOT}/python-ds
      commandLine: python -m venv .venv && . .venv/bin/activate && python app.py
      group:
        kind: run
